### ISSUE TITLE
server hangs on clone when specifying --depth=1

### ISSUE THREAD

**Issue by csrwng** [AaronO/go-git-http#22]
The issue is the same as this one on gogs:
https://github.com/gogits/gogs/issues/236

**Comment by AaronO** [comment]
@csrwng Thanks that makes sense. It's a shame that the errors are silenced though.

**Comment by shurcooL** [comment]
Isn't it still available via the `EventHandler` callback?

https://github.com/AaronO/go-git-http/blob/34209cf6cd947cfa52063bcb0f6d43cfa50c5566/githttp.go#L134
