### ISSUE TITLE
Duplicate Path

### ISSUE THREAD

**Issue by IronPark** [AaronO/go-git-http#9]
this is my code.
```go
	repoPath := filepath.ToSlash(filepath.Join(wkdir.WorkingDir(),"repo"))
	gitHandler := githttp.New(repoPath)
	temp, err := gitHandler.Init()
	if err != nil {
		panic(err)
	}

	gitHandler.GitBinPath = "C:/Program Files (x86)/Git/bin/git"
	goji.Get("/repo/*", temp)
	goji.Post("/repo/*", temp)
	goji.Serve()
```
```
git clone localhost:8000/repo/testing.git
```
->
Repo not found on disk 
GetFileAttributesEx D:/GOPATH/src/JustGo/`repo`/`repo`/testing.git: The system cannot find the path specified.

**Comment by AaronO** [comment]
@IronPark `go-git-http` looks at `req.URL.Path` and appends that to `repoPath` (in your case, generally what is passed to `githttp.New`)

It looks like `repoPath == "D:/GOPATH/src/JustGo/repo"` and the URL you're cloning from is `repo/testing.git`

So when both are combined that generates: `D:/GOPATH/src/JustGo/repo/repo/testing.git`

So you have two fixes:

1. Remove `/repo` from your `repoPath` like:
```
repoPath := filepath.ToSlash(wkdir.WorkingDir())
```

2. Use `http.StripPrefix` (like shown here: http://play.golang.org/p/4-kyRTrdd9)
```
goji.Get("/repo/*", http.StripPrefix("/repo/", temp))
```

I recommend doing `2.` :) Good luck :+1:
